Repository COS301-SE-2025/Marito, pull requests merged in 2025-05, with the labels that each got.

#35 registration V1.0.0.0 of the login , Registration and landing page of the UI
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/public/DFSI_Logo.png
  frontend/public/LS_image.png
  frontend/public/vite.svg
  frontend/src/App.tsx
  frontend/src/assets/react.svg
  frontend/src/components/auth/AnimatedGreeting.tsx
  frontend/src/index.css
  frontend/src/main.tsx
  frontend/src/pages/LandingPage.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/RegistrationPage.tsx
  frontend/src/styles/AnimatedGreeting.css
  frontend/src/styles/LandingPage.css
  frontend/src/styles/LoginPage.css
  frontend/src/styles/RegistrationPage.css
Labels: implementation

#44 docs: add user stories and use case diagrams for search and gamification features
  Documentation/UseCaseDiagrams/GamifictionUseCase.png
  Documentation/UseCaseDiagrams/SearchTermUseCase.png
  Documentation/UseCaseSpecification/GamificationUseCaseSpec.md
  Documentation/UseCaseSpecification/GamificationUseCaseSpec.pdf
  Documentation/UseCaseSpecification/SearchTermUseCaseSpec.md
  Documentation/UseCaseSpecification/SearchTermUseCaseSpec.pdf
  Documentation/UserStories/GamificationUserSotry.pdf
  Documentation/UserStories/GamificationUserStory.md
  Documentation/UserStories/SearchTermUserStory.md
  Documentation/UserStories/SearchTermUserStory.pdf
  Documentation/UserStories/UpvoteSubSystemUserStory.md
  Documentation/UserStories/dataVisualizationUserStory.md
  Mock_Data/multilingual_statistical_terminology_clean.json
Labels: documentation

#73 Feature/backend gc ps
  backend/.gitignore
  backend/Dockerfile
  backend/app/__init__.py
  backend/app/api/__init__.py
  backend/app/api/deps.py
  backend/app/api/v1/__init__.py
  backend/app/api/v1/api.py
  backend/app/api/v1/endpoints/__init__.py
  backend/app/api/v1/endpoints/auth.py
  backend/app/core/__init__.py
  backend/app/core/config.py
  backend/app/core/security.py
  backend/app/crud/__init__.py
  backend/app/crud/crud_user.py
  backend/app/db/__init__.py
  backend/app/db/base.py
  backend/app/db/base_class.py
  backend/app/db/session.py
  backend/app/main.py
  backend/app/models/__init__.py
  backend/app/models/language.py
  backend/app/models/user.py
  backend/app/schemas/__init__.py
  backend/app/schemas/token.py
  backend/app/schemas/user.py
  backend/requirements.txt
  backend/tests/test_sample.py
  frontend/package-lock.json
  frontend/package.json
  frontend/src/main.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/RegistrationPage.tsx
  frontend/vite.config.ts
Labels: Systems

#88 Feature/term frequency
  backend/Makefile
  backend/app/__pycache__/main.cpython-312.pyc
  backend/app/api/deps.py
  backend/app/api/v1/api.py
  backend/app/api/v1/endpoints/__pycache__/auth.cpython-312.pyc
  backend/app/api/v1/endpoints/auth.py
  backend/app/api/v1/endpoints/search.py
  backend/app/core/__pycache__/config.cpython-312.pyc
  backend/app/core/__pycache__/security.cpython-312.pyc
  backend/app/core/config.py
  backend/app/core/security.py
  backend/app/crud/__pycache__/crud_user.cpython-312.pyc
  backend/app/crud/crud_search.py
  backend/app/crud/crud_user.py
  backend/app/db/__pycache__/base.cpython-312.pyc
  backend/app/db/__pycache__/base_class.cpython-312.pyc
  backend/app/db/__pycache__/session.cpython-312.pyc
  backend/app/db/base.py
  backend/app/db/base_class.py
  backend/app/db/session.py
  backend/app/main.py
  backend/app/models/__pycache__/language.cpython-312.pyc
  backend/app/models/__pycache__/user.cpython-312.pyc
  backend/app/models/language.py
  backend/app/models/user.py
  backend/app/schemas/__pycache__/token.cpython-312.pyc
  backend/app/schemas/__pycache__/user.cpython-312.pyc
  backend/app/schemas/comment.py
  backend/app/schemas/term.py
  backend/app/schemas/token.py
  backend/app/schemas/user.py
  backend/app/tests/test_search.py
Labels: enhancement
